### ISSUE TITLE
'roomId' is not defined 

### ISSUE THREAD

**Issue by abhinaisai2002** [marshadkhn/CURLS#10]
**Describe the bug**

src\pages\editorPage.js
  Line 17:11:  'roomId' is not defined 

**To Reproduce**
1. Start the react dev server

**Expected behavior**
roomId should be declared some where or take input from the user

**Screenshots**
![Screenshot 2023-09-30 225058](https://github.com/marshadkhn/CURLS/assets/70501952/87ea67a6-b677-47a3-a772-463df2293797)

**Comment by marshadkhn** [comment]
Already opened and assign
Issue number -  #7
