### ISSUE TITLE
Would Like to convert project from javascript to typescript

### ISSUE THREAD

**Issue by Swarajballal** [marshadkhn/CURLS#23]
The repository contains code written in JavaScript, and I would like to propose converting it to TypeScript to enhance code maintainability, readability, and developer experience.

**Describe the solution you'd like**
I would like to propose a solution where the JavaScript code in the repository is refactored and converted into TypeScript. This conversion should include adding type annotations, interfaces, and other necessary TypeScript features to improve code quality and maintainability.

**Comment by geeky-sambhav** [comment]
Sounds great go for it
