### ISSUE TITLE
feat: Updating the side logo in workspace

### ISSUE THREAD

**Issue by marshadkhn** [marshadkhn/CURLS#25]
# Hacktoberfest 2023
When you get into the workspace on the left top there is only the curly brackets logo, we are looking to update this thing
Design something related to coding 

Screenshots
![image](https://github.com/marshadkhn/CURLS/assets/80325579/cec79b69-d2a0-4f8d-b139-c9af0a42dd0d)

**Comment by CBID2** [comment]
What do you have in mind as far as design @marshadkhn?

**Comment by marshadkhn** [comment]
> What do you have in mind as far as design @marshadkhn?
something related to coding like the clean and simple

**Comment by INFIZEUS** [comment]
Hey,
I have a design idea to update your logo. I believe these changes could enhance the visual representation of your brand. Please let me know a convenient time for you to discuss this further.

**Comment by marshadkhn** [comment]
Nope I don't want to redesign the logo
Just want a better thing on left top

**Comment by kaligone** [comment]
> Nope I don't want to redesign the logo Just want a better thing on left top

You want the complete new logo or Enhancements in current logo?

**Comment by INFIZEUS** [comment]
@marshadkhn So other than the Logo part, you need like some stuffing at the left corner related to coding. 
Should it be an image, logo, or just text?

**Comment by marshadkhn** [comment]
> @marshadkhn So other than the Logo part, you need like some stuffing at the left corner related to coding. 
> Should it be an image, logo, or just text? 

Exclude text 
Something image or other stuff

**Comment by marshadkhn** [comment]
> > Nope I don't want to redesign the logo Just want a better thing on left top
> 
> You want the complete new logo or Enhancements in current logo?

Just put something unique there
