### ISSUE TITLE
Copy Room ID Button Fix 

### ISSUE THREAD

**Issue by aj12-houdini** [marshadkhn/CURLS#26]
### Bug 
When you click on the "Copy Room ID" button, the ID doesn't actually get copied to the clipboard. 

**To Reproduce**
1. After you log in and create a room 
2. Click on 'Copy Room ID'
3. See error

**Expected behavior**
The ID should be copied to the clipboard

**Comment by geeky-sambhav** [comment]
> ### Bug 
> When you click on the "Copy Room ID" button, the ID doesn't actually get copied to the clipboard. 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. After you log in and create a room 
> 2. Click on 'Copy Room ID'
> 3. See error
> 
> **Expected behavior**
> The ID should be copied to the clipboard
> 
> 

Would u like to fix this?

**Comment by aj12-houdini** [comment]
> > ### Bug
> > When you click on the "Copy Room ID" button, the ID doesn't actually get copied to the clipboard.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. After you log in and create a room
> > 2. Click on 'Copy Room ID'
> > 3. See error
> > 
> > **Expected behavior**
> > The ID should be copied to the clipboard
> 
> Would u like to fix this?

Yeah I would love to.
