### ISSUE TITLE
[BUG] Leave Room button not working

### ISSUE THREAD

**Issue by RahulGIT24** [marshadkhn/CURLS#27]
**Describe the bug**
The leave button on the editor page is not working

**To Reproduce**
1. Create an function that will navigate user back to /
2. Fire that function when someone click on leave room button

I would like to work on that issue.

**Comment by geeky-sambhav** [comment]
> **Describe the bug** The leave button on the editor page is not working
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create an function that will navigate user back to /
> 2. Fire that function when someone click on leave room button
> 
> I would like to work on that issue.

Ok go for it

**Comment by RahulGIT24** [comment]
Can you mark it as Hacktoberfest accepted

**Comment by geeky-sambhav** [comment]
> Can you mark it as Hacktoberfest accepted

done
