### ISSUE TITLE
Adding username to editor's page 

### ISSUE THREAD

**Issue by kubical12** [marshadkhn/CURLS#33]
**Is your feature request related to a problem? Please describe.**
I would like to add this feature , from which the entered username is displayed in the editors page . 

**Describe the solution you'd like**

I have added screenshot kindly check and if you like assign me this issue under hacktoberfest .
![Screenshot (2)](https://github.com/marshadkhn/CURLS/assets/110725429/14d085f5-1d6c-4a91-8c7a-33cdf8356fc0)

**Comment by marshadkhn** [comment]
Good issue

**Comment by marshadkhn** [comment]
Advice for future - when you work on any issue and your PR is merged just close the issue
