### ISSUE TITLE
update ReadMe

### ISSUE THREAD

**Issue by iqrafirdose** [marshadkhn/CURLS#39]
ReadMe is a file that everyone sees to understand about the project. There are some typos in the readme file. I would like to correct it.

**Comment by iqrafirdose** [comment]
Can you please assign the issue to me under Hackthoberfest ?

**Comment by marshadkhn** [comment]
please describe your issue completely

**Comment by marshadkhn** [comment]
> please describe your issue completely

and IG hackto is ended

**Comment by iqrafirdose** [comment]
> please describe your issue completely

There are some spelling mistakes in the Readme file.

**Comment by iqrafirdose** [comment]
> > please describe your issue completely
> 
> and IG hackto is ended

Ohh, Okay
