### ISSUE TITLE
Join button is not working

### ISSUE THREAD

**Issue by marshadkhn** [marshadkhn/CURLS#4]
**Describe the bug**
When you login or create a room, **JOIN** button is not working

**To Reproduce**
1. Go to 'your IDE'
2. Run the app
3. The front page will appear on that page see the 'Join' button

**Expected behavior**
When you click on join it will automatically create the room for you

**Screenshots**
![image](https://github.com/marshadkhn/CURLS/assets/80325579/01ab5b14-375f-45d6-82ba-0c3c916d761f)

**Comment by ronisarkarexe** [comment]
@marshadkhn could you please assign this issue to me under Hacktoberfest. I am really interested in working on it.

**Comment by marshadkhn** [comment]
**Don't send your pull request before 1 oct it will not counted by hacktoberfest org.**

**Comment by Mdfarhan9304** [comment]
Can you assign this issue to me. I like to work on it
