### ISSUE TITLE
Duplicate workspace

### ISSUE THREAD

**Issue by marshadkhn** [marshadkhn/CURLS#5]
**Describe the bug**
There are two workspaces when you **join** the room

**To Reproduce**
1. Go to 'your IDE and start the app'
2. Click on 'search bar'
3. Edit the URL , change the route `http://localhost:3000/editor/<your-roomID>`

**Expected behavior**
There should be only one workspace in the web app

**Screenshots**
![FireShot Capture 010 - CURLS - localhost](https://github.com/marshadkhn/CURLS/assets/80325579/ab6a5ac1-af69-4ddc-b1c2-d2a732fbc4e6)

**Comment by ronisarkarexe** [comment]
@marshadkhn Could you please assign me this task also?

**Comment by 1-ankush-1** [comment]
@marshadkhn can you assign this to me.

**Comment by marshadkhn** [comment]
Assigned this to @1-ankush-1 for the sake of more and more engagement

**Remember don't send your PR before 1 October your pull request will not be counted by hacktoberfest org.**

**Comment by 1-ankush-1** [comment]
> Assigned this to @1-ankush-1 for the sake of more and more engagement
> 
> **Remember don't send your PR before 1 October your pull request will not be counted by hacktoberfest org.**

hyy server doesn't have event listeners and at client side it is not emmiting any event when create room function is called.
