### ISSUE TITLE
Editor not able to access roomId

### ISSUE THREAD

**Issue by 1-ankush-1** [marshadkhn/CURLS#7]
**Describe the bug**
There is a issue with roomId the component is not able to access the roomId

**To Reproduce**
1.setup the project
2.start the react app
3.open http://localhost:3000/
4. you will see the error

**Expected behavior**
It should able to access the roomId 

**Screenshots**
![image](https://github.com/marshadkhn/CURLS/assets/95346389/ac1eb7c7-c8b0-4a2b-8522-62e5ef573aad)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser : chrome
 - Version : 117

**Additional context**
I would like to take this issue.

**Comment by marshadkhn** [comment]
Send PR after 1 oct

**Comment by ronisarkarexe** [comment]
@marshadkhn i already solve this issue
