### ISSUE TITLE
Enhance User Interface and Responsiveness

### ISSUE THREAD

**Issue by mukul1107** [marshadkhn/CURLS#9]
This includes updates to both JavaScript and CSS to enhance the visual appeal, usability, and responsiveness of various components. Here are the key changes:

### JSX Changes

-Improved the behavior of the "Create Room" button.
-Enhanced mouse interaction for better user experience.
-Can Add the dynamic cursor if the screen is touch supportive.
-Updated event handling for cursor movement.

### CSS Changes

-Styling enhancements for buttons, inputs, and overall layout.
-Improved responsiveness for various screen sizes.
-Equalized text size and spacing between specific elements.
-Hover effects for interactive components.
-Organized and documented CSS for easier maintenance.

**Comment by marshadkhn** [comment]
Sure, but when you change the user interface please look for issues - #4 , #5 and #7 make sure you pr should not conflict with these issues and send your pr after 1 oct

**Comment by mukul1107** [comment]
all right mate!

**Comment by marshadkhn** [comment]
> all right mate!

Better to communicate with these peeps and send a quality PR

**Comment by mukul1107** [comment]
User Can now create and join the room. 

Improved responsiveness
